apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ghost-nordcloud.fullname" . }}
  labels:
    app: {{ include "ghost-nordcloud.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "ghost-nordcloud.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "ghost-nordcloud.fullname" . }}
    spec:
      containers:
      - name: {{ include "ghost-nordcloud.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 2368
          protocol: TCP
        env:
        - name: url
          value: {{ .Values.service.url }}

        - name: database__client
          value: {{ .Values.database.client }}

        - name: database__connection__host
          value: {{ .Values.database.connection.host }}

        - name: database__connection__user
          value: {{ .Values.database.connection.user | quote }}

        - name: database__connection__password
          value: {{ .Values.database.connection.password | quote }}
          # valueFrom:
          #   secretKeyRef:
          #     name: mysql-secret
          #     key: db-password
          

        - name: database__connection__database
          value: {{ .Values.database.connection.database }}

        - name: database__connection__ssl__ca
          value: {{ .Values.database.connection.ssl.ca | quote }}

        - name: database__connection__port
          value: {{ .Values.database.connection.port | quote }}

        - name: database__connection__ssl__rejectUnauthorized
          value: {{ .Values.database.connection.ssl.rejectUnauthorized | quote }}

        - name: NODE_EXTRA_CA_CERTS
          value: "/etc/ssl-cert"

      #   volumeMounts:
      #   - name: secrets-store01-inline
      #     mountPath: "/mnt/secrets-store"
      #     readOnly: true
        
      # volumes:
      #   - name: secrets-store01-inline
      #     csi:
      #       driver: secrets-store.csi.k8s.io
      #       readOnly: true
      #       volumeAttributes:
      #         secretProviderClass: "azure-sync"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      